# Generated by Django 2.0.3 on 2018-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('degree', models.CharField(blank=True, max_length=30)),
                ('degree_subject', models.CharField(blank=True, max_length=30)),
                ('current_role', models.CharField(blank=True, max_length=30)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('tq_value', models.IntegerField(null=True)),
                ('tq_score', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(blank=True)),
                ('membership_date', models.DateTimeField(blank=True, null=True)),
                ('num_skills', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TQ', models.FloatField(default=0.0, verbose_name=' Trust Quotient ')),
                ('skill1', models.CharField(blank=True, max_length=50, verbose_name=' Skill #1 ')),
                ('skill2', models.CharField(blank=True, max_length=50, verbose_name=' Skill #2 ')),
                ('skill3', models.CharField(blank=True, max_length=50, verbose_name=' Skill #3 ')),
                ('skill4', models.CharField(blank=True, max_length=50, verbose_name=' Skill #4 ')),
                ('skill5', models.CharField(blank=True, max_length=50, verbose_name=' Skill #5 ')),
                ('degree', models.CharField(blank=True, max_length=50)),
                ('min_num_skills', models.IntegerField(default=1, verbose_name=' Minimum Number of Skills ')),
                ('years_experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='skills',
            field=models.ManyToManyField(blank=True, to='Expert.Skills'),
        ),
    ]
